pipeline {
    agent any

    stages {
        stage('Maven Version') {
            steps {
                sh 'mvn -version'
            }
        }
        stage('Python3 Version') {
            steps {
                sh 'python3 --version'
            }
        }
        stage('Java Version') {
            steps {
                sh 'java -version'
            }
        }
        stage('Terraform Version') {
            steps {
                sh 'terraform --version'
            }
        }
        stage('AWS Version') {
            steps {
                sh 'aws --version'
            }
        }
        stage('Pip Version') {
            steps {
                sh 'pip3 --version'
            }
        }
    }
}
